### PR TITLE
got map loaded on page, had to disable deezer js script

### PR DESCRIPTION
**Pull request by jAndreassi**
First map up on site.

### CODE REVIEW

**Review by ColdWeatherBoyy — CHANGES_REQUESTED** [review]
Hey it looks like there's a few conflicts in the index.html. Can you please pull the main into your branch and resolve any conflicts so we can add this in?

**Comment by jAndreassi** [comment]
Fixed conflicts, please check now.

**Review by ColdWeatherBoyy — APPROVED** [review]
Works over here!

**Comment by ColdWeatherBoyy** [comment]
Good work team

**Pull request merged**
